# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    provider "aws" {
        region = "ap-south-1"
        profile = "terraform-sunny"

        assume_role {
            role_arn = "arn:aws:iam::396608771618:role/terraform-role"
        }
    }
