# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket   = "terraformsunny"
    encrypt  = true
    key      = "./terraform.tfstate"
    profile  = "terraform-sunny"
    region   = "ap-south-1"
    role_arn = "arn:aws:iam::396608771618:role/terraform-role"
  }
}
